services:
  web:
    build:
      context: ./webapp/
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - database

  database:
    build:
      context: ./database/
      dockerfile: Dockerfile
    image: mysql:mylatest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: movie123
